# Generated by Django 4.0.3 on 2022-04-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
