# Generated by Django 4.0.3 on 2022-04-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_short_desc_blog_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='tittle',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='tittle',
        ),
    ]
