# Generated by Django 4.0.3 on 2022-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_title_blog_tittle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
