# Generated by Django 4.0.3 on 2022-04-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_comment_post_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='total_comments',
            new_name='total',
        ),
    ]
