# Generated by Django 4.0.3 on 2022-04-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_rename_total_comments_blog_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='blog',
        ),
    ]
