# Generated by Django 4.0.3 on 2022-05-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_rename_comments_comment_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='total',
            new_name='comment_count',
        ),
    ]
