# Generated by Django 4.0.3 on 2022-05-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_rename_total_blog_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_count',
        ),
    ]
