# Generated by Django 4.0.3 on 2022-03-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('body', models.TextField(blank=True, null=True)),
                ('author', models.CharField(default='Admin', max_length=70)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('status', models.CharField(choices=[('deactive', 'Deactive'), ('active', 'Active')], max_length=50)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
