# Generated by Django 4.0.3 on 2022-03-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',), 'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
    ]
